name: Commit to Repository2

on:
  push:
    branches:
      - main # Adjust branch name if needed

jobs:
  commit_to_repository2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository2
        uses: actions/checkout@v2
        with:
          repository: jamescardona11/personal-page
          token: ${{ secrets.SS_TOKEN }}
          ref: main
          submodules: 'recursive'

      - name: Update submodule
        run: |
          cd src/content/posts
          git pull origin main --ff -f

      - name: Create commit
        run: |
          echo "$(date)" >> automated.txt
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add automated.txt
          git commit -m "Automated commit triggered by changes in blog-posts. - $(date)"
          git push
